name: Storage
version: 1.0.0 
main: es.mithrandircraft.storage.StoragePlugin
description: With this plugin you can save items in a SQLite or MySQL Database for each player
author: [xX_andrescol_Xx]
api-version: 1.15
website: www.mithrandircraft.es
commands:
  sopen: 
    description: Open the storage 
    permission-message: '[Storage] You dont haver permission for this command'
    permission: storage.open.other
    usage: Incorrect usage, try /sopen <player>
permissions: 
  storage.sopen: {description: Allow to open other players storage, default: op}
      
    